# Generated by Django 4.2.11 on 2024-05-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank='profile/faq.png', upload_to='profile'),
        ),
    ]
